#!/usr/bin/env bash

#  Copyright 2019 Stanislav Senotrusov <stan@senotrusov.com>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

set -o nounset

REPO_VOLUME="/home/ubuntu/kelly"
# REPO_PATH=""
REPO_NAME="stan-data-pi-backup"

PASSPHRASE_FILE="${REPO_VOLUME}/.${REPO_NAME}.passphrase"
KEY_EXPORT_DIR="${REPO_VOLUME}/notes/keys/borg-keys"

BORG_BASE_DIR="${REPO_VOLUME}"

RCLONE_REMOTE="onedrive"
RCLONE_PATH="backups"
RCLONE_EXTRA_ARGS="--bwlimit 400k"
RCLONE_STATE_DIR="${REPO_VOLUME}/.cache/backup-rclone-state/${REPO_NAME}"
RCLONE_CONFIG="${REPO_VOLUME}/.config/rclone/rclone.conf"

# LAUNCHD_LABEL=""
# SYSTEMD_NAME=""

# CHECKPOINT=""

make-backup() {
  PREFIX="" FROM_PATH="/home/ubuntu/kelly" add-files notes
}
