#!/bin/sh

#  Copyright 2012-2016 Stanislav Senotrusov <stan@senotrusov.com>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.echo "\n  Raspberry Pi\n"

# https://www.funtoo.org/Raspberry_Pi_Userland_(VCGENCMD)

echo -n "  "
vcgencmd get_throttled || { echo "Unable to vcgencmd get_throttled ($?)" >&2; }

echo -n "  "
vcgencmd measure_temp || { echo "Unable to vcgencmd measure_temp ($?)" >&2; }

for i in core sdram_c sdram_i sdram_p; do
  echo "  ${i}_$(vcgencmd measure_volts "${i}" || { echo "Unable to vcgencmd measure_volts ${i} ($?)" >&2; })"
done

echo ""

sudo smartctl -H -A -l error /dev/sda || { echo "Unable to smartctl /dev/sda ($?)" >&2; }
